# Pandas basic practice
### Series:

In [44]:
import numpy as np
import pandas as pd

In [45]:
# Tạo pandas từ series:
nd_s1=np.array([1,2,3,4]) 
type(nd_s1)

numpy.ndarray

In [29]:
nd_s1

array([1, 2, 3, 4])

In [33]:
nd_s1[0]

1

In [32]:
nd_s1[1:3]

array([2, 3])

In [34]:
nd_s1[-2]

3

In [39]:
nd_s1[-3:-1]

array([2, 3])

In [28]:
pd_s1=pd.Series(nd_s1)
type(pd_s1)

pandas.core.series.Series

In [40]:
pd_s1.head(4)

0    1
1    2
2    3
3    4
dtype: int32

In [49]:
nd_s2=pd..Series([1,2,3,4],index=['a','b','c','d'])
type(nd_s2)

pandas.core.series.Series

In [50]:
nd_s2

a    1
b    2
c    3
d    4
dtype: int64

In [53]:
nd_s2['a']

1

In [54]:
nd_s2[0]

1