In [1]:
import numpy as np

![](https://i.stack.imgur.com/NWTQH.png)

#### 1. Create array

In [2]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr = np.array([1, 2, 3, 'Truong'])
arr

array(['1', '2', '3', 'Truong'], dtype='<U21')

In [5]:
arr = np.array([1, 2, 3], dtype='float')
arr

array([1., 2., 3.])

In [6]:
arr.shape

(3,)

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype='float')
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [8]:
arr.shape

(3, 3)

In [9]:
arr = np.array([[[1, 2], [3, 4], [5, 6]], 
                [[7, 8], [9, 10], [11, 12]], 
                [[13, 14], [15, 16], [17, 8]]], dtype='float')
arr

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.],
        [17.,  8.]]])

In [10]:
arr.shape

(3, 3, 2)

In [24]:
np.linspace(1, 10, 20).reshape(2, 2, 5)

array([[[ 1.        ,  1.47368421,  1.94736842,  2.42105263,
          2.89473684],
        [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,
          5.26315789]],

       [[ 5.73684211,  6.21052632,  6.68421053,  7.15789474,
          7.63157895],
        [ 8.10526316,  8.57894737,  9.05263158,  9.52631579,
         10.        ]]])

In [15]:
arr = np.linspace(1, 10_000_000, 10_000_000).reshape(5000, 2000)
arr

array([[1.000000e+00, 2.000000e+00, 3.000000e+00, ..., 1.998000e+03,
        1.999000e+03, 2.000000e+03],
       [2.001000e+03, 2.002000e+03, 2.003000e+03, ..., 3.998000e+03,
        3.999000e+03, 4.000000e+03],
       [4.001000e+03, 4.002000e+03, 4.003000e+03, ..., 5.998000e+03,
        5.999000e+03, 6.000000e+03],
       ...,
       [9.994001e+06, 9.994002e+06, 9.994003e+06, ..., 9.995998e+06,
        9.995999e+06, 9.996000e+06],
       [9.996001e+06, 9.996002e+06, 9.996003e+06, ..., 9.997998e+06,
        9.997999e+06, 9.998000e+06],
       [9.998001e+06, 9.998002e+06, 9.998003e+06, ..., 9.999998e+06,
        9.999999e+06, 1.000000e+07]])

In [17]:
np.savetxt('test.txt', arr)

In [18]:
arr_2 = np.loadtxt('test.txt')
arr_2

array([[1.000000e+00, 2.000000e+00, 3.000000e+00, ..., 1.998000e+03,
        1.999000e+03, 2.000000e+03],
       [2.001000e+03, 2.002000e+03, 2.003000e+03, ..., 3.998000e+03,
        3.999000e+03, 4.000000e+03],
       [4.001000e+03, 4.002000e+03, 4.003000e+03, ..., 5.998000e+03,
        5.999000e+03, 6.000000e+03],
       ...,
       [9.994001e+06, 9.994002e+06, 9.994003e+06, ..., 9.995998e+06,
        9.995999e+06, 9.996000e+06],
       [9.996001e+06, 9.996002e+06, 9.996003e+06, ..., 9.997998e+06,
        9.997999e+06, 9.998000e+06],
       [9.998001e+06, 9.998002e+06, 9.998003e+06, ..., 9.999998e+06,
        9.999999e+06, 1.000000e+07]])

In [19]:
arr_2.shape

(5000, 2000)

In [25]:
np.zeros((3, 3, 2), dtype='int')

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [ ]:
li = list(range(11))

In [28]:
li = list(range(11))
new_li = [0 for i in range(6)]
print(new_li)

index = 0 
for i in li:
    if i % 2 == 0:
        new_li[index] = i
        index += 1
new_li

[0, 0, 0, 0, 0, 0]


[0, 2, 4, 6, 8, 10]

In [ ]:
np.linalg.