In [2]:
import numpy as np

%config completer.use_jedi=false

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
type(arr)

numpy.ndarray

In [6]:
arr=np.array([1,2,3,'Truong'])
arr

array(['1', '2', '3', 'Truong'], dtype='<U11')

In [7]:
arr=np.array([1,2,3], dtype='float')
arr

array([1., 2., 3.])

In [8]:
arr.shape

(3,)

In [9]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)

In [10]:
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [11]:
arr.shape

(3, 3)

In [12]:
arr=np.array([[[1,2],[3,4],[5,6]],
              [[7,8],[9,10],[11,12]],
              [[13,14],[15,16],[17,18]]], dtype='float')

In [13]:
arr

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.],
        [17., 18.]]])

In [14]:
arr.shape

(3, 3, 2)