In [1]:
import numpy as np

%config completer.use_jedi=false

In [2]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
type(arr)

numpy.ndarray

In [19]:
arr.dtype.name

'float64'

In [26]:
type(arr)

numpy.ndarray

In [4]:
arr=np.array([1,2,3,'Truong'])
arr

array(['1', '2', '3', 'Truong'], dtype='<U11')

In [5]:
arr=np.array([1,2,3], dtype='float')
arr

array([1., 2., 3.])

In [6]:
arr.shape

(3,)

In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)

In [8]:
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [9]:
arr.shape

(3, 3)

In [10]:
arr=np.array([[[1,2],[3,4],[5,6]],
              [[7,8],[9,10],[11,12]],
              [[13,14],[15,16],[17,18]]], dtype='float')

In [20]:
arr

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.],
        [17., 18.]]])

In [12]:
arr.shape

(3, 3, 2)

In [21]:
arr.shape

(3, 3, 2)

In [22]:
arr.size

18

In [23]:
arr.dtype

dtype('float64')

In [24]:
arr.dtype.itemsize

8

In [25]:
arr.itemsize

8

In [29]:
a=np.linspace(10,30,5)
a

array([10., 15., 20., 25., 30.])

In [30]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [31]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
>>> b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [34]:
c = np.array([[1.5, 2, 3], [4, 5, 6]])
>>> c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [35]:
np.array([1,2,3])

array([1, 2, 3])

In [36]:
np.empty((1,2))

array([[-1.23698584e-036,  4.98156672e+210]])

In [40]:
np.zeros_like(, dtype='float')

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [43]:
x=np.arange(6,dtype=np.int64)
x=x.reshape(3,2)
np.zeros_like(x,dtype='float')

array([[0., 0.],
       [0., 0.],
       [0., 0.]])