In [2]:
import numpy as np

%config completer.use_jedi=false

In [2]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
type(arr)

numpy.ndarray

In [19]:
arr.dtype.name

'float64'

In [26]:
type(arr)

numpy.ndarray

In [4]:
arr=np.array([1,2,3,'Truong'])
arr

array(['1', '2', '3', 'Truong'], dtype='<U11')

In [5]:
arr=np.array([1,2,3], dtype='float')
arr

array([1., 2., 3.])

In [6]:
arr.shape

(3,)

In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)

In [8]:
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [9]:
arr.shape

(3, 3)

In [10]:
arr=np.array([[[1,2],[3,4],[5,6]],
              [[7,8],[9,10],[11,12]],
              [[13,14],[15,16],[17,18]]], dtype='float')

In [20]:
arr

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.],
        [17., 18.]]])

In [12]:
arr.shape

(3, 3, 2)

In [21]:
arr.shape

(3, 3, 2)

In [22]:
arr.size

18

In [23]:
arr.dtype

dtype('float64')

In [24]:
arr.dtype.itemsize

8

In [25]:
arr.itemsize

8

In [29]:
a=np.linspace(10,30,5)
a

array([10., 15., 20., 25., 30.])

In [30]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [31]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
>>> b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [34]:
c = np.array([[1.5, 2, 3], [4, 5, 6]])
>>> c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [35]:
np.array([1,2,3])

array([1, 2, 3])

In [36]:
np.empty((1,2))

array([[-1.23698584e-036,  4.98156672e+210]])

In [40]:
np.zeros_like(, dtype='float')

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [43]:
x=np.arange(6,dtype=np.int64)
x=x.reshape(3,2)
np.zeros_like(x,dtype='float')

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
np.full((2,5),6,dtype='float')

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [5]:
x=[1,2]

In [6]:
x

[1, 2]

In [7]:
np.asarray(x)

array([1, 2])

In [10]:
X = np.array([[1, 2], [3, 4]])
np.asmatrix(X)

matrix([[1, 2],
        [3, 4]])

In [12]:
x=np.array([30])
x.item()

30

In [13]:
x=np.array([30])
x[0]

30

In [14]:
np.arange(2,102,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [18]:
np.linspace(3.,10.)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [19]:
np.linspace(3.,10.,50,endpoint=False)

array([3.  , 3.14, 3.28, 3.42, 3.56, 3.7 , 3.84, 3.98, 4.12, 4.26, 4.4 ,
       4.54, 4.68, 4.82, 4.96, 5.1 , 5.24, 5.38, 5.52, 5.66, 5.8 , 5.94,
       6.08, 6.22, 6.36, 6.5 , 6.64, 6.78, 6.92, 7.06, 7.2 , 7.34, 7.48,
       7.62, 7.76, 7.9 , 8.04, 8.18, 8.32, 8.46, 8.6 , 8.74, 8.88, 9.02,
       9.16, 9.3 , 9.44, 9.58, 9.72, 9.86])

In [30]:
a=np.array([[9, 7],
       [5, 2]])
b=np.array([[1, 9],
       [5, 1]])
(np.hstack((a,b)))

array([[9, 7, 1, 9],
       [5, 2, 5, 1]])

In [31]:
x=np.array([[1,2,3], [4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
print(np.vstack((x,y)))
print(np.vstack((x,y)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
x=np.array(np.arange(1,10))
np.array_split(x,(4,6))

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]