## Bài 1.

Viết một chương trình tính giai thừa của một số nguyên dương n. Với n được nhập từ bàn phím. Ví dụ, n = 8 thì kết quả đầu ra phải là `1*2*3*4*5*6*7*8` = 40320.

In [70]:
n = int(input("Input positive integer: "))
 
def factorial(n):
    if n == 0:
        return 1
    else: 
        return n*factorial(n-1)
 
print (n,'! =',(factorial(n)))

Input positive integer:  8


8 ! = 40320


In [71]:
# Testing
n = 5
assert factorial(n) == 120, "Wrong answer, please calculate again"

## Bài 2.

Viết chương trình tính tổng của các chữ số của môt số nguyên n trong Python. Số nguyên dương n được nhập từ bàn phím. Với n = 1234, tổng các chữ số: 1 + 2 + 3 + 4 = 10

In [15]:
int(-123/10)

-12

In [22]:
n = int(input("Nhập số nguyên n = "));

def sum_all(n):
    SUM = 0;
    while (n > 0):
        SUM += n % 10; #SUM = SUM + n % 10
        n = int(n / 10)
    return SUM

print("Tổng các chữ số của", n , "là",  sum_all(n));

Nhập số nguyên n =  1234


Tổng các chữ số của 1234 là 10


In [68]:
# Testing
number = 34103
assert sum_all(number) == 11, "Wrong answer, please calculate again"

## Bài 3.

Tìm giá trị lớn nhất của một list hoặc tuple nhập vào

In [10]:
n = int(input("Number of elements : "))
l1st = []
for i in range(0,n):
    l1st.append(int(input('Input list values:')))
print(l1st)
def maximum(l1st):
    return max(l1st)
print("The maximum value is:",maximum(l1st))

    

Number of elements :  3
Input list values: 2
Input list values: 3
Input list values: 4


[2, 3, 4]
The maximum value is: 4


In [67]:
# Testing
number = [1, 2, 6, 8, 10]
assert maximum(number) == 10, "Wrong answer, please calculate again"

## Bài 4.

Tìm giá trị lớn thứ nhì từ một list hoặc tuple nhập vào

In [9]:
def second_maximum(l1):
    l2=l1.copy()
    l2.remove(max(l2))
    return max(l2)
n=int(input('Number of elements?'))
l1=[]
for i in range(0,n):
    l1.append(int(input('Input list value:')))
print('The second maximum value in the list:',second_maximum(l1))

Number of elements? 4
Input list value: 1
Input list value: 2
Input list value: 3
Input list value: 4


second maximum value in the list: 3


In [66]:
# Testing
number = [1, 2, 6, 8, 10]
assert second_maximum(number) == 8, "Wrong answer, please calculate again"

## Bài 5.

Định nghĩa một hàm có input là 2 chuỗi và trả về chuỗi có độ dài lớn hơn. Nếu 2 chuỗi có chiều dài như nhau thì trả tất cả các chuỗi dưới dạng tuple

In [73]:
def greater_string(str_1, str_2):
    if len(str_1)>len(str_2):
        return str_1
    elif len(str_1)<len(str_2):
        return str_2
    else:
        result=(str_1,str_2)
        return tuple(result)
str_1=input('nhập chuỗi 1:')
str_2=input('nhập chuỗi 2:')
print(greater_string(str_1, str_2))

nhập chuỗi 1: 1
nhập chuỗi 2: 1


('1', '1')


In [75]:
# Test 1
str_1 = "My name is"
str_2 = "My university"

assert len(greater_string(str_1, str_2)) == len(str_2), "Wrong answer, please code again"


#Test 2

str_1 = "My name is"
str_2 = "My name ar"

assert greater_string(str_1, str_2) == (str_1, str_2), "Wrong answer, please code again"

## Bài 6.

Loại bỏ các giá trị trùng từ chuỗi nhập vào, nhưng vẫn giữ thứ tự.

Ví dụ: aaabbbbcccddd1111 --> abcd1

In [64]:
def remove_duplicated(str_1):
    str_2=str_1[0]
    for a in str_1[1:]:
        if a != str_2[-1]:
            str_2=str_2+a
    return str_2
c=input('Input:')
print('Output:',remove_duplicated(c))

Input: 1112


Output: 12


In [62]:
# Testing
str_1 = "cccccddddeeeeffff22222"

assert remove_duplicated(str_1) == "cdef2"

## Bài 7. 
Viết một chương trình có 2 chữ số X, Y nhận giá trị đầu vào và tạo ra một mảng 2 chiều. Giá trị phần tử trong hàng thứ i và cột thứ j của mảng phải là `i*j`

Lưu ý: 
- i = 0, 1, 2, ..., X-1
- j = 0, 1, 2, ..., Y-1      

In [29]:
import numpy as np
def create_2D_array(X, Y):
    column=[]
    for i in range(0,x):
        row=[]
        for j in range(0,y):
            row.append(i*j)
        column.append(row)
    return column
x=int(input('x:'))
y=int(input('y:'))
result = np.array(create_2D_array(x,y))
print(create_2D_array(x,y))
print(result)

x: 3
y: 5


[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


In [17]:
assert create_2D_array(5, 5) == [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8], [0, 3, 6, 9, 12], [0, 4, 8, 12, 16]], "Wrong answer, please code again"

## Bài 8.
Viết chương trình để xuất một số ngẫu nhiên, chia hết cho 5 và 7, từ 0 đến 200 (gồm cả 0 và 200), sử dụng module random và list comprehension

In [328]:
import random
def division_5_7(random_seed = 4):
    random.seed(random_seed)
    # Your code here
    return 
import random

random.seed(10)
print(random.random())

0.5714025946899135


In [87]:
random_seed = 4
assert division_5_7(random_seed) == 35, "Wrong answer, please code again"

NameError: name 'division_5_7' is not defined

In [34]:
import random
def getnums(start, end, interval):
   return list(range(start, end, interval))
start, end, interval = 0, 201,35
li = list(getnums(start, end,interval))
print("Ket qua:",random.choice(li))

Ket qua: 70
