## Bài 1.

Viết một chương trình tính giai thừa của một số nguyên dương n. Với n được nhập từ bàn phím. Ví dụ, n = 8 thì kết quả đầu ra phải là `1*2*3*4*5*6*7*8` = 40320.

In [20]:
def factorial(n):
    result = 1
    if n == 0:
        return result
    else:
        for i in range (1,n+1):
            result = result*i
    return result

In [27]:
factorial(5)

120

## Bài 2.

Viết chương trình tính tổng của các chữ số của môt số nguyên n trong Python. Số nguyên dương n được nhập từ bàn phím. Với n = 1234, tổng các chữ số: 1 + 2 + 3 + 4 = 10

In [41]:
def sum_all(number):
    sum_ = 0
    for i in range (0,number+1):
        sum_= i+sum_
    return sum_

In [35]:
sum_all(4)

10

In [ ]:
# Testing
number = 34103
assert sum_all(number) == 11, "Wrong answer, please calculate again"

## Bài 3.

Tìm giá trị lớn nhất của một list hoặc tuple nhập vào

In [1]:
def maximum(li):
    max_ = li[0]
    a = len(li)
    for i in range(1,a):
        if max_< li[i]:
            max_= li[i]
        else:
            break
    return max_

In [55]:
maximum([8,1,2,3,4,5,6,])

8

In [ ]:
# Testing
number = [1, 2, 6, 8, 10]
assert maximum(number) == 10, "Wrong answer, please calculate again"

## Bài 4.

Tìm giá trị lớn thứ nhì từ một list hoặc tuple nhập vào

In [23]:
def second_maximum(li):
    a=maximum(li)
    li1=li.remove(a)
    secon_max= maximum(li)
    return secon_max

In [26]:
second_maximum([1,2,3,4,5,6,7])

6

In [ ]:
# Testing
number = [1, 2, 6, 8, 10]
assert second_maximum(number) == 8, "Wrong answer, please calculate again"

## Bài 5.

Định nghĩa một hàm có input là 2 chuỗi và trả về chuỗi có độ dài lớn hơn. Nếu 2 chuỗi có chiều dài như nhau thì trả tất cả các chuỗi dưới dạng tuple

In [8]:
def greater_string(str_1, str_2):
    if len(str_1)> len(str_2):
        return str_1
    if len (str_1)<len(str_2):
        return str_2
    if len(str_1)==len(str_2):
        return (str_1,str_2)

In [9]:
greater_string("MY NAM IS LOGN","MY UNIVERSITY IS BACKKHOA")

'MY UNIVERSITY IS BACKKHOA'

In [10]:
greater_string("MY UNIVERSITY IS BACKKHOA","MY UNIVERSITY IS BACKKHOA")

('MY UNIVERSITY IS BACKKHOA', 'MY UNIVERSITY IS BACKKHOA')

## Bài 6.

Loại bỏ các giá trị trùng từ chuỗi nhập vào, nhưng vẫn giữ thứ tự.

Ví dụ: aaabbbbcccddd1111 --> abcd1

In [144]:
def remove_duplicated(str_1):
    result = ''
    for i in str_1:
        if i not in result:
            result += i
    return result
c=input('Input:')
print('Output:',remove_duplicated(c))

Input: aaabbbbccc


Output: abc


In [ ]:
# Testing
str_1 = "cccccddddeeeeffff22222"

assert remove_duplicated(str_1) == "cdef2"

## Bài 7. 
Viết một chương trình có 2 chữ số X, Y nhận giá trị đầu vào và tạo ra một mảng 2 chiều. Giá trị phần tử trong hàng thứ i và cột thứ j của mảng phải là `i*j`

Lưu ý: 
- i = 0, 1, 2, ..., X-1
- j = 0, 1, 2, ..., Y-1      

In [145]:
import numpy as np
def create_2D_array(X, Y):
    column=[]
    for i in range(0,x):
        row=[]
        for j in range(0,y):
            row.append(i*j)
        column.append(row)
    return column
x=int(input('x:'))
y=int(input('y:'))
result = np.array(create_2D_array(x,y))
print(create_2D_array(x,y))
print(result)

x: 3
y: 4


[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6]]
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]]


In [ ]:
def create_2D_array(X, Y):
    # Your code here
    return 

In [ ]:
assert create_2D_array(5, 5) == [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8], [0, 3, 6, 9, 12], [0, 4, 8, 12, 16]], "Wrong answer, please code again"

## Bài 8.
Viết chương trình để xuất một số ngẫu nhiên, chia hết cho 5 và 7, từ 0 đến 200 (gồm cả 0 và 200), sử dụng module random và list comprehension

In [ ]:
import random
def division_5_7(random_seed = 4):
    random.seed(random_seed)
    # Your code here
    return 
    

In [ ]:
random_seed = 4
assert division_5_7(random_seed) == 35, "Wrong answer, please code again"