In [2]:
import numpy as np

### Create a new array of 3*2 float numbers, filled with ones.

In [6]:
arr_1=np.array([[1,1],
              [1,1],
              [1,1]], dtype='float')
arr_1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
arr_2=np.zeros([3,2],dtype='int')
arr_2

array([[0, 0],
       [0, 0],
       [0, 0]])

In [31]:
y=np.arange(6,dtype='float') #Tạo list 6 phẩn tử kiểu số thực lần lượt có giá trị từ 0 đến 5
x=np.reshape(y,[3,2]) # chuyển về ma trận kích thước 3x2 mà không là thay đổi dữ liệu có trong list y
arr_2=np.ones_like(x, dtype='float') #tạo ma trận có các phần tử =1 kiểu số thực có kích thước giống ma trận x
arr_2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Let `x = np.arange(4, dtype=np.int64)`. Create an array of ones with the same shape and type as X.
### Hint: uses `np.ones_like()`

In [39]:
x=np.arange(4,dtype='int')
arr_3=np.ones_like(x,dtype='int')
arr_3

array([1, 1, 1, 1])

### Create a new array of 3*2 float numbers, filled with zeros.

In [46]:
arr_4=np.zeros([3,2], dtype='float')
arr_4

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.
### Hint: use `np.zeros_like()`

In [62]:
# Hỏi: dtype=np.int64 khác gì dtype='int'???
x=np.arange(4,dtype='int')
arr_5=np.zeros_like(x,dtype='int')
print('X:',x)
print('Mảng zero có kích thước tương tự X:',arr_5)

X: [0 1 2 3]
Mảng zero có kích thước tương tự X: [0 0 0 0]


### Create a new array of shape 2*5 , filled with 6.

In [87]:
li=[6 for i in range(10)] #Tạo list chứa 10 phẩn tử có giá trị 6
x=np.matrix(li) #chuyển list thành matrix
arr_6=np.reshape(x,[2,5]) #thay đổi kích cỡ matrix
arr_6

matrix([[6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6]])

### Create an array of [1, 2, 3].

In [85]:
arr_7=np.array([i for i in range(1,4)])
arr_7

array([1, 2, 3])

### Let x = [1, 2]. Convert it into an array.
### Hint: use `np.asarray()`

In [84]:
# Hỏi: np.array khác gì np.asarray???
x=[1,2]
arr_8=np.asarray(x) #Convert list thành array
arr_8

array([1, 2])

### Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.
### Hint: use `np.asmatrix()`

In [91]:
x=np.array([i for i in range(1,5)]) #Tạo x
arr_9=np.reshape(x,[2,2]) 
matrix_1=np.asmatrix(arr_9)
matrix_1

matrix([[1, 2],
        [3, 4]])

### Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.
### Hint: use `x.item()` or `x[0]`

In [95]:
x=np.array([30])
x[0]

30

### Create an array of 2, 4, 6, 8, ..., 100.

In [3]:
arr_10=np.arange(2,101,2)
arr_10

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [4]:
arr_10=np.array([i for i in range(2,101,2)])
arr_10

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.
### Hint: use `np.linspace()`

In [111]:
np.linspace(3,10,dtype='float')

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

### Create a 1-D array of 50 element spaced evenly between 3. and 10., exclude 10.
### Hint: add parameter `endpoint=False`

In [131]:
arr_11=np.linspace(3,10,num=10,endpoint=False)
arr_11

array([3. , 3.7, 4.4, 5.1, 5.8, 6.5, 7.2, 7.9, 8.6, 9.3])

Lex x be an array  
`[[ 1 2 3],
[ 4 5 6]]`.

and y be an array  
`[[ 7 8 9],
[10 11 12]]`.

Concatenate x and y so that a new array looks like  
`[[1, 2, 3, 7, 8, 9],
[4, 5, 6, 10, 11, 12]]`.

In [145]:
x=np.reshape([i for i in range(1,7)],[2,3])
y=np.reshape([i for i in range(7,13)],[2,3])
z=np.concatenate((x,y),axis=1)
z

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Concatenate x and y so that a new array looks like  
`[[ 1  2  3],
 [ 4  5  6],
 [ 7  8  9],
 [10 11 12]]`.

In [146]:
x=np.reshape([i for i in range(1,7)],[2,3])
y=np.reshape([i for i in range(7,13)],[2,3])
z=np.concatenate((x,y),axis=0)
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [148]:
x=np.reshape([i for i in range(1,7)],[2,3])
y=np.reshape([i for i in range(7,13)],[2,3])
z=np.concatenate((x,y),axis=None)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [146]:
x=np.reshape([i for i in range(1,7)],[2,3])
y=np.reshape([i for i in range(7,13)],[2,3])
z=np.concatenate((x,y),axis=0)
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [168]:
x=np.reshape([i for i in range(1,7)],[2,3])
y=np.reshape([i for i in range(7,13)],[2,3])
z=np.concatenate((x,y),axis=0)
a=z[3][2]   
a

12

In [15]:
#????

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [187]:
x=np.array([i for i in range(1,10)])
y=np.split(x,[4,6,9])
y

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9]), array([], dtype=int32)]