## Bài 04 (Tiếp)

#### 3.2.2. While 
```
while condition (True/False):
    business logic
```
##### String format

In [2]:
a='Ha'
'Hello {}'.format(a)

'Hello Ha'

In [3]:
a,b='Ha','plesures'
'Hello {} with all my {}'.format(a,b)

'Hello Ha with all my plesures'

In [4]:
f'Hello {a} with all my {b}'

'Hello Ha with all my plesures'

In [5]:
# %s ->string, %d ->decimal, %f -> float
'Hello %s with age %d' %('Ha',20)

'Hello Ha with age 20'

* for dùng cho các vòng lặp xác định.

* while nên dùng khi số vòng lặp chưa xác định

#### 3.3. Condition
```
if condition (True/False):
    busiiness logic
elif condition:
    business logic
...
else:
    business logic
```

In [9]:
a,b=3,1
if a<b:
    print('a<b')
elif a>b:
    print('a>b')
else:
    print('a=b')

a>b


#### 4. Function
```
def function_name(agr_1,agr_2,...,agr_n):
    business logic
    return result
```

In [11]:
def lengh_of_list(li):
    count=0
    for _ in li: #Biến chạy không dùng để tính toán thì để dạng _ cũng được
        count+=1
    return count
lengh_of_list([1,4,7,9])

4

In [13]:
lengh_of_list({1,4,7,9,10})

5

In [14]:
lengh_of_list('ha noi')

6

In [16]:
# sum chỉ tính tổng các phần tử kiểu số
def sum(li):
    sum=0
    for ele in li:
        if type(ele)==int:
            sum+=ele
    return sum
sum(['10',2,4,6])

12

In [16]:
#sum2 tính tổng các phần tử kiểu số hoặc ký tự dạng số
def sum2(li):
    sum=0
    for ele in li:
        if type(ele)==int:
            sum+=ele
        if type(ele)==str and ele.isdigit():
            sum+=
    return sum
sum(['10',2,4,6])

12

In [18]:
def average(li):
    sum=0
    count=0
    for ele in li:
        if type(ele)==int:
            sum+=ele
            count+=1
    return sum/count
average(['10',2,4,6])

4.0

In [24]:
# tìm các số nguyên tố trong list:
def prime_number(number):
    re=True
    for ele in range(2,number):
        if number%ele==0:
            re=False
            break
    return re

li=[6,7,15,29,192,126437,67]
print('Các phần tử là số nguyên tố trong trong list:')
for ele1 in li:
    if prime_number(ele1):
        print(ele1)

Các phần tử là số nguyên tố trong trong list:
7
29
67


* lambda dùng xây dựng nhanh các hàm tính toán đơn giản

In [36]:
# Anonymous funciton -> Noname
squared=lambda x:x**2

In [37]:
squared(5)

25

### 5. Comprehension
* Chỉ nên dùng comprehention cho các bộ dữ liệu vừa và nhỏ vì tốc độ chậm (Do dữ liệu được load lên tất cả 1 lần nên dễ bị tràn RAM nếu dữ liệu lớn)
* Dữ liệu lớn: traditional loop

In [39]:
li=list(range(1,21))

li

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [41]:
# Tạo list mới chỉ các phần tử có giá trị chẵn trong li
#viết code
new_li=[]
for ele in li:
    if ele%2==0:
        new_li.append(ele)
new_li

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [43]:
# Tạo list mới chỉ các phần tử có giá trị chẵn trong li
#dùng comprehention
[ele for ele in li if ele%2==0]

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [46]:
# Tạo list mới mà các phần tử lẻ chuyển sang bình phương, chẵn giữ nguyên trong li
#dùng comprehention
[ele**2 if ele%2!=0 else ele for ele in li]

[1, 2, 9, 4, 25, 6, 49, 8, 81, 10, 121, 12, 169, 14, 225, 16, 289, 18, 361, 20]

In [48]:
li2=list(range(-5,5))
li2

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]

In [49]:
#nagative: abs
#Positive: remain
[abs(ele) if ele <0 else -ele for ele in li2]

[5, 4, 3, 2, 1, 0, -1, -2, -3, -4]

In [50]:
#nagative: quare
#Positive: remain
[ele**2 if ele <0 else -ele for ele in li2]

[25, 16, 9, 4, 1, 0, -1, -2, -3, -4]

In [54]:
li3=[[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]]
li3

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [55]:
# nghiên cứu thêm tình huống này
[i for sub_li in li3 for i in sub_li if i%2!=0]

[1, 3, 5, 7, 9, 11]

# Bài 04:
## Numpy
* Dùng để xử lý dữ liệu ma trận nhiều chiều
* Ma trận chỉ chứa duy nhất 1 kiểu dữ liệu.

![](https://d2h0cx97tjks2p.cloudfront.net/blogs/wp-content/uploads/sites/2/2020/07/NumPy-Broadcasting.jpg)

### 1. Create array:

In [59]:
import numpy as np

In [60]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [61]:
arr.shape # xem kích thước ma trận

(3,)

In [64]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
arr2.shape # xem kích thước ma trận

(2, 3)

In [68]:
arr3=np.array([[[1,2],[3,4],[5,6]],
                [[7,8],[9,10],[11,12]],
              [[13,14],[15,16],[17,18]]], dtype='float')
arr3

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.],
        [17., 18.]]])

In [69]:
arr3.shape # xem kích thước ma trận

(3, 3, 2)

In [74]:
arr3[1][2]

array([11., 12.])

In [80]:
#hàm linspace tạo ra 1 ma trận với khoảng cách
# hàm reshape dùng để đổi chiều mà trận
arr4=np.linspace(1,10,20)
arr4


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [81]:
np.savetxt('text.txt',arr4)

In [84]:
arr5=np.loadtxt('text.txt')
arr5

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [90]:
arr5.shape

(20,)

In [91]:
# Tạo ma trận 0
np.zeros([3,3,2], dtype='int')

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])