# Mathematical functions

In [23]:
import numpy as np
import math

In [3]:
np.__version__

'1.19.2'

## Trigonometric functions

Calculate sine, cosine, and tangent of x, element-wise.  
Hint: use np.sin(), np.cos(), np.tan()

In [27]:
# Đáp án thầy sai?!
x = np.array([0., 1., 30,60,90])
print('Sin:',np.round(np.sin(x*np.pi/180),3))
print('Cosin:', np.round(np.cos(x*np.pi/180),3))
print('Tan:',np.round(np.tan(x*np.pi/180 ),3))
print('Tan=Sin/Cos:',np.round(np.sin(x*np.pi/180)/np.cos(x*np.pi/180),3))

Sin: [0.    0.017 0.5   0.866 1.   ]
Cosin: [1.    1.    0.866 0.5   0.   ]
Tan: [0.00000000e+00 1.70000000e-02 5.77000000e-01 1.73200000e+00
 1.63312394e+16]
Tan=Sin/Cos: [0.00000000e+00 1.70000000e-02 5.77000000e-01 1.73200000e+00
 1.63312394e+16]


Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.  
Hint: use np.arcsin(), np.arccos(), np.arctan()

In [37]:
x = np.array([-1.,-0.5, 0,0.5, 1.])
print('arcsin:',np.round(np.arcsin(x)*180/np.pi,3))
print('arccos:',np.round(np.arccos(x)*180/np.pi,3))
print('arctan:',np.round(np.arctan(x)*180/np.pi,3))

arcsin: [-90. -30.   0.  30.  90.]
arccos: [180. 120.  90.  60.   0.]
arctan: [-45.    -26.565   0.     26.565  45.   ]


Convert angles from radians to degrees.  
Hint: use np.degrees() or np.rad2deg()

In [46]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
print(np.degrees(x))
print(np.rad2deg(x))

[-180.  -90.   90.  180.]
[-180.  -90.   90.  180.]


Convert angles from degrees to radians.  
Hint: use np.radians() or np.deg2rad()

In [47]:
x = np.array([-180.,  -90.,   90.,  180.])
print(np.radians(x))
print(np.deg2rad(x))

[-3.14159265 -1.57079633  1.57079633  3.14159265]
[-3.14159265 -1.57079633  1.57079633  3.14159265]


## Hyperbolic functions

Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.  
Hint: use np.sinh(), np.cosh(), np.tanh()

In [49]:
x = np.array([-1., 0, 1.])
print('hyperbolic sine:',np.sinh(x))
print('hyperbolic cosine:',np.cosh(x))
print('hyperbolic tangent:',np.tanh(x))

hyperbolic sine: [-1.17520119  0.          1.17520119]
hyperbolic cosine: [1.54308063 1.         1.54308063]
hyperbolic tangent: [-0.76159416  0.          0.76159416]


## Rounding

Round x element-wise  
Hint: use np.around(x) or np.floor(x) or np.ceil(x) or np.trunc(x)

In [60]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])
print(np.around(x,2))
print(np.round(x,2))
print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))

[ 2.1  1.5  2.5  2.9 -2.1 -2.5 -2.9]
[ 2.1  1.5  2.5  2.9 -2.1 -2.5 -2.9]
[ 2.  1.  2.  2. -3. -3. -3.]
[ 3.  2.  3.  3. -2. -2. -2.]
[ 2.  1.  2.  2. -2. -2. -2.]


## Sums, products, differences

Calculate the difference between neighboring elements, element-wise.  
Hint: use np.diff()

In [63]:
x = np.array([1, 2, 4, 7, 0])
print(np.diff(x))

[ 1  2  3 -7]


- Return the cross product of x and y.  (Tích chéo của x và y)
- Hint: use np.cross()

In [66]:
# Xem lại về tích chéo?!
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.cross(x,y))

[-3  6 -3]


## Exponents and logarithms

Compute $e^x$, element-wise.  
Hint: use np.exp()

In [69]:
x = np.array([-1.,0.,1., 2., 3.], np.float32)
print(np.exp(x))

[ 0.36787945  1.          2.7182817   7.389056   20.085537  ]


Calculate exp(x) - 1 for all elements in x.  
Hint: there are np.expm1() and np.exp(), make your own choice and use it properly

In [70]:
x = np.array([1., 2., 3.], np.float32)
print(np.expm1(x))

[ 1.7182817  6.389056  19.085537 ]


Calculate $2^p$ for all p in x.  
Hint: Refer to the lecture. np.exp2() will help, too.

In [80]:
x = np.array([-2,-1,0,0.5,1., 2., 3.,4,5.], np.float64)
print(np.exp2(x))

[ 0.25        0.5         1.          1.41421356  2.          4.
  8.         16.         32.        ]


In [77]:
print(np.sqrt(2))

1.4142135623730951


Compute natural, base 10, and base 2 logarithms of x element-wise.  
Hint: use np.log(), np.log10(), np.log2()

In [81]:
x = np.array([1, np.e, np.e**2])
print('natural log: ',np.log(x))
print('common log: ',np.log10(x))
print('base 2 log: ',np.log2(x))

natural log:  [0. 1. 2.]
common log:  [0.         0.43429448 0.86858896]
base 2 log:  [0.         1.44269504 2.88539008]


## Arithmetic operations

Add x and y element-wise.

In [99]:
x = np.array([1, 2, 3,5])
y = np.array([-1, -2, -3,-4])
print(np.add(x,y))
print(x+y)
print((x+y)[3])

[0 0 0 1]
[0 0 0 1]
1


Subtract y from x element-wise. (Các phần tử trong mảng x trừ giá trị y)

In [98]:
x = np.array([3, 4, 5,13])
y = np.array(3)
print(np.subtract(x,y))
print(x-y)


[ 0  1  2 10]
[ 0  1  2 10]


Multiply x by y or x by z element-wise.

In [97]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])
z=np.array(3)
print(np.multiply(x,y))
print(x*y)
print(np.multiply(x,z))

[ 3  0 -5]
[ 3  0 -5]
[ 9 12 15]


Divide x by y element-wise

In [96]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])
z=np.array(3)
print(np.divide(x,y))
print(x/y)
print(np.divide(x,z))

[3.         2.         1.66666667]
[3.         2.         1.66666667]
[1.         1.33333333 1.66666667]


Compute numerical negative value of x, element-wise.

In [91]:
x = np.array([1, -1])
print(np.negative(x))

[-1  1]


Compute the reciprocal of x, element-wise.

In [92]:
x = np.array([1., 2., .2])
print(np.reciprocal(x))

[1.  0.5 5. ]


Compute $x^y$, element-wise.

In [95]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
z=np.array(3)
print(np.power(x,y))
print(x**y)
print(np.power(x,z))

[[ 1  4]
 [ 3 16]]
[[ 1  4]
 [ 3 16]]
[[ 1  8]
 [27 64]]


Compute the remainder of x / y element-wise in two different ways.  
Hint: use np.mod() or `%` operator

In [100]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2
print(np.mod(x,y))
print(x%y)

[1 0 1 1 0 1]
[1 0 1 1 0 1]


## Miscellaneous

If an element of x is smaller than 3, replace it with 3.  
And if an element of x is bigger than 7, replace it with 7.  
Hint: use array masking

In [102]:
x = np.arange(10)
print('x before:',x)
x[x<3]=3
x[x>7]=7
print('x after replace:',x)

x before: [0 1 2 3 4 5 6 7 8 9]
x after replace: [3 3 3 3 4 5 6 7 7 7]


In [116]:
y=np.array([np.int(np.random.rand()*100) for i in range(1,100)])
print('y before:\n',y)
y[y%2==0]=0
print('y after replace:\n',y)


y before:
 [44 58 95 50 79 46 53 43 30 47 71 49 80 45 20 66 34 75 56 92 76  1 29 61
 91 66 64 71 79 25 99 36 85 92 84 52 97 79  6 27 85 31 17 62 10 37 28 11
 19 46 71  0 43 94 88 43 81  0 48 16 28 44  6 26 14 72 27 71 56 80  6 83
 26 91 48 42 47 46 18 61 16 18 93 40 20 71 40 15 17 87 81 62 65 84 14 44
 41 18 77]
y after replace:
 [ 0  0 95  0 79  0 53 43  0 47 71 49  0 45  0  0  0 75  0  0  0  1 29 61
 91  0  0 71 79 25 99  0 85  0  0  0 97 79  0 27 85 31 17  0  0 37  0 11
 19  0 71  0 43  0  0 43 81  0  0  0  0  0  0  0  0  0 27 71  0  0  0 83
  0 91  0  0 47  0  0 61  0  0 93  0  0 71  0 15 17 87 81  0 65  0  0  0
 41  0 77]


Compute the square of x, element-wise.

In [119]:
x = np.array([1, 2, -1,5])
print(np.square(x))
print(x**2)

[ 1  4  1 25]
[ 1  4  1 25]


Compute square root of x element-wise.

In [120]:
x = np.array([1., 4., 9.])
print(np.sqrt(x))
print(x**(1/2))

[1. 2. 3.]
[1. 2. 3.]


Compute the absolute value of x.

In [11]:
x = np.array([[1, -1], [3, -3]])
x=np.abs(x)
x

array([[1, 1],
       [3, 3]])

Compute an element-wise indication of the sign of x, element-wise.

In [27]:
x = np.array([1, 3, 0, -1, -3])
x=np.indices()

[ 1  1  0 -1 -1]
