# Mathematical functions

In [44]:
import numpy as np

In [3]:
np.__version__

'1.19.2'

## Trigonometric functions

Calculate sine, cosine, and tangent of x, element-wise.  
Hint: use np.sin(), np.cos(), np.tan()

In [50]:
# Đáp án thầy sai?!
x = np.array([0., 1., 30,60,90])
print('Sin:',np.sin(x*np.pi/180))
print('Cosin:', np.cos(x*np.pi/180))
print('Tan:',np.tan(x*np.pi/180 ))
print('Tan=Sin/Cos:',np.sin(x*np.pi/180)/np.cos(x*np.pi/180))

Sin: [0.         0.01745241 0.5        0.8660254  1.        ]
Cosin: [1.00000000e+00 9.99847695e-01 8.66025404e-01 5.00000000e-01
 6.12323400e-17]
Tan: [0.00000000e+00 1.74550649e-02 5.77350269e-01 1.73205081e+00
 1.63312394e+16]
Tan=Sin/Cos: [0.00000000e+00 1.74550649e-02 5.77350269e-01 1.73205081e+00
 1.63312394e+16]


In [18]:
np.pi

3.141592653589793

Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.  
Hint: use np.arcsin(), np.arccos(), np.arctan()

In [5]:
x = np.array([-1., 0, 1.])
x

array([-1.,  0.,  1.])

Convert angles from radians to degrees.  
Hint: use np.degrees() or np.rad2deg()

In [6]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
x

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

Convert angles from degrees to radians.  
Hint: use np.radians() or np.deg2rad()

In [6]:
x = np.array([-180.,  -90.,   90.,  180.])

[-3.14159265 -1.57079633  1.57079633  3.14159265]


## Hyperbolic functions

Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.  
Hint: use np.sinh(), np.cosh(), np.tanh()

In [7]:
x = np.array([-1., 0, 1.])

[-1.17520119  0.          1.17520119]
[1.54308063 1.         1.54308063]
[-0.76159416  0.          0.76159416]


## Rounding

Round x element-wise  
Hint: use np.around(x) or np.floor(x) or np.ceil(x) or np.trunc(x)

In [8]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])

[ 2.  2.  2.  3. -2. -2. -3.]
[ 2.  1.  2.  2. -3. -3. -3.]
[ 3.  2.  3.  3. -2. -2. -2.]
[ 2.  1.  2.  2. -2. -2. -2.]


## Sums, products, differences

Calculate the difference between neighboring elements, element-wise.  
Hint: use np.diff()

In [9]:
x = np.array([1, 2, 4, 7, 0])

[ 1  2  3 -7]


Return the cross product of x and y.  
Hint: use np.cross()

In [10]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

[-3  6 -3]


## Exponents and logarithms

Compute $e^x$, element-wise.  
Hint: use np.exp()

In [11]:
x = np.array([1., 2., 3.], np.float32)

[ 2.7182817  7.389056  20.085537 ]


Calculate exp(x) - 1 for all elements in x.  
Hint: there are np.expm1() and np.exp(), make your own choice and use it properly

In [12]:
x = np.array([1., 2., 3.], np.float32)

[ 1.7182817  6.389056  19.085537 ]


Calculate $2^p$ for all p in x.  
Hint: Refer to the lecture. np.exp2() will help, too.

In [13]:
x = np.array([1., 2., 3.], np.float32)

[2. 4. 8.]


Compute natural, base 10, and base 2 logarithms of x element-wise.  
Hint: use np.log(), np.log10(), np.log2()

In [14]:
x = np.array([1, np.e, np.e**2])

natural log = [0. 1. 2.]
common log = [0.         0.43429448 0.86858896]
base 2 log = [0.         1.44269504 2.88539008]


## Arithmetic operations

Add x and y element-wise.

In [15]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])

[0 0 0]


Subtract y from x element-wise.

In [16]:
x = np.array([3, 4, 5])
y = np.array(3)

[0 1 2]


Multiply x by y element-wise.

In [17]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])

[ 3  0 -5]


Divide x by y element-wise

In [18]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])

[3.         2.         1.66666667]


Compute numerical negative value of x, element-wise.

In [19]:
x = np.array([1, -1])

[-1  1]


Compute the reciprocal of x, element-wise.

In [20]:
x = np.array([1., 2., .2])

[1.  0.5 5. ]


Compute $x^y$, element-wise.

In [21]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])

[[ 1  4]
 [ 3 16]]


Compute the remainder of x / y element-wise in two different ways.  
Hint: use np.mod() or `%` operator

In [22]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2

[1 0 1 1 0 1]


## Miscellaneous

If an element of x is smaller than 3, replace it with 3.  
And if an element of x is bigger than 7, replace it with 7.  
Hint: use array masking

In [23]:
x = np.arange(10)

[3 3 3 3 4 5 6 7 7 7]


Compute the square of x, element-wise.

In [24]:
x = np.array([1, 2, -1])

[1 4 1]


Compute square root of x element-wise.

In [25]:
x = np.array([1., 4., 9.])

[1. 2. 3.]


Compute the absolute value of x.

In [11]:
x = np.array([[1, -1], [3, -3]])
x=np.abs(x)
x

array([[1, 1],
       [3, 3]])

Compute an element-wise indication of the sign of x, element-wise.

In [27]:
x = np.array([1, 3, 0, -1, -3])
x=np.indices()

[ 1  1  0 -1 -1]
